version: '3'
services:

  service1:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=myStr0ngP4ssw0rd
    labels:
        crono: "* * * * *"

  service2:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=myStr0ngP4ssw0rd
    labels:
        crono: "@hourly"

  service3:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=myStr0ngP4ssw0rd
    labels:
        crono: "5 0 * 8 *"

  service4:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=myStr0ngP4ssw0rd
    labels:
        test: "28 * * * *"

  service5:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=myStr0ngP4ssw0rd


  service6:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=myStr0ngP4ssw0rd
    labels:
        crono: "*/3 * * * *"

  crono:
    build:
      context: ./src/
      #dockerfile: Dockerfile_Builder # to generate the docker image to docker hub
      dockerfile: Dockerfile_Compiler # to tests
    restart: always
    volumes:
      - "./docker-compose.yml:/app/docker-compose.yml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./logs/crono/:/app/logs/"
    
    environment: 
      - TZ=America/Sao_Paulo
      - WAIT=3
  
