version: '3'
services:

 
  crono:
    build:
      context: .
      dockerfile: Dockerfile_x64_x86 # OR Dockerfile_arm64
    restart: always
    volumes:
      - "./docker-compose.yml:/app/docker-compose.yml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment: 
      - TIMEZONE=America/Cuiaba
      - WAIT=3
  
  